- length: 100
  hikers:
    - name: A
      speed: 100
    - name: B
      speed: 50
    - name: C
      speed: 20
    - name: D
      speed: 10 
- length: 100
  hikers:
    - name: A
      speed: 100
    - name: B
      speed: 25
    - name: C
      speed: 20
    - name: D
      speed: 15   
- length: 250
  hikers:
    - name: A
      speed: 100
    - name: B
      speed: 50
    - name: C
      speed: 20
    - name: D
      speed: 10
    - name: E
      speed: 2.5
- length: 250
  hikers:
    - name: F
      speed: 25
    - name: G
      speed: 15